-- Distributed transaction for deleting a passenger.
-- PARAMS:
--  - P_PASSENGER_ID : id of passenger to be deleted.
CREATE OR REPLACE PROCEDURE DELETE_PASSENGER
(
    P_PASSENGER_ID IN NUMBER
) AS
v_user_exists number;
BEGIN
    SELECT COUNT(1) INTO v_user_exists FROM PASSENGER WHERE ID_PASSENGER = P_PASSENGER_ID;
    if v_user_exists = 0 then
        RAISE_APPLICATION_ERROR(-20000, '{No user found}');
    else
        DELETE FROM TICKET WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM PASSENGER WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM TICKET@AMERICA WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM PASSENGER@AMERICA WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM TICKET@ASIA WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM PASSENGER@ASIA WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM TICKET@OCEANIA WHERE ID_PASSENGER = P_PASSENGER_ID;
        DELETE FROM PASSENGER@OCEANIA WHERE ID_PASSENGER = P_PASSENGER_ID;
        COMMIT;
    end if;
END DELETE_PASSENGER;
/