INSERT INTO CONTINENT
SELECT *
FROM CONTINENTFULL;

INSERT INTO COUNTRY
SELECT COUNTRYFULL.id_country, COUNTRYFULL.id_continent, COUNTRYFULL.name
FROM COUNTRYFULL;

INSERT INTO CITY
SELECT CITYFULL.id_city, CITYFULL.id_country, CITYFULL.name
FROM CITYFULL;

INSERT INTO AIRPORT
SELECT AIRPORTFULL.id_airport, AIRPORTFULL.id_city, AIRPORTFULL.name
FROM AIRPORTFULL;

INSERT INTO ROUTE
SELECT ROUTEFULL.id_route, ROUTEFULL.id_airport_departure, ROUTEFULL.id_airport_arrival, ROUTEFULL.route_duration
FROM ROUTEFULL, AIRPORTFULL, CITYFULL, COUNTRYFULL, CONTINENTFULL
WHERE ROUTEFULL.id_airport_departure = AIRPORTFULL.id_airport 
    AND AIRPORTFULL.id_city = CITYFULL.id_city
    AND CITYFULL.id_country = COUNTRYFULL.id_country
    AND COUNTRYFULL.id_continent = CONTINENTFULL.id_continent
    AND CONTINENTFULL.id_continent = &1;

INSERT INTO SCHEDULETIME
SELECT *
FROM SCHEDULETIMEFULL;

INSERT INTO AIRPLANE
SELECT *
FROM AIRPLANEFULL;

INSERT INTO PASSENGER
SELECT *
FROM PASSENGERFULL;

INSERT INTO FLIGHT
SELECT FLIGHTFULL.id_flight, FLIGHTFULL.id_route, FLIGHTFULL.id_schedule, FLIGHTFULL.id_plane, FLIGHTFULL.price, FLIGHTFULL.flight_date, FLIGHTFULL.on_time
FROM FLIGHTFULL, ROUTEFULL, AIRPORTFULL, CITYFULL, COUNTRYFULL, CONTINENTFULL
WHERE FLIGHTFULL.id_route = ROUTEFULL.id_route
    AND ROUTEFULL.id_airport_departure = AIRPORTFULL.id_airport
    AND AIRPORTFULL.id_city = CITYFULL.id_city
    AND CITYFULL.id_country = COUNTRYFULL.id_country
    AND COUNTRYFULL.id_continent = CONTINENTFULL.id_continent
    AND CONTINENTFULL.id_continent = &1;

DROP TABLE TicketFull;
DROP TABLE FlightFull;
DROP TABLE ScheduleTimeFull;
DROP TABLE RouteFull;
DROP TABLE AirportFull;
DROP TABLE CityFull;
DROP TABLE CountryFull;
DROP TABLE ContinentFull;
DROP TABLE PassengerFull;
DROP TABLE AirplaneFull;